# Site settings
title: 二度ある事は三度目正直
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  技術的なネタをひたすらメモるブログ
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ytk.github.io/" # the base hostname & protocol for your site
twitter_username: staccato
github_username:  ytk

# Build settings
markdown: kramdown
